apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lazyops-day5-day6
commonLabels:
  app.kubernetes.io/part-of: lazyops
  lazyops.platform-bundle: day5-day6
commonAnnotations:
  lazyops.platform/managed-by: lazyops
  lazyops.platform/ingress-class: traefik
resources:
  - 00-namespace-standards.yaml
  - 10-port-matrix.yaml
