apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lazyops-day7-day8
commonLabels:
  app.kubernetes.io/part-of: lazyops
  lazyops.platform-bundle: day7-day8
resources:
  - 00-namespace-agent-access.yaml
  - 10-internal-dns-smoke.yaml
