apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lazyops-system
resources:
  - 00-lazyops-system.yaml
  - 01-traefik-helmchartconfig.yaml
  - 02-node-agent-rbac.yaml
  - 03-node-agent-secret.template.yaml
  - 04-registry-secret.template.yaml
  - 05-node-agent-daemonset.yaml
